# Configuration file for HyDE
# Environment variables should be on top
# Updated config.toml file can be found at $HOME/.local/share/hyde/config.toml

"$schema" = "https://raw.githubusercontent.com/HyDE-Project/HyDE/refs/heads/master/Configs/.local/share/hyde/schema/config.toml.json"

# sysmonlaunch.sh configuration.
[sysmonitor]
execute = "btop"
commands = ["btop", "htop", "top"]
terminal = "kitty"

# Hyprland configuration.
[hyprland]
browser = "zen-browser"  # Browser.
editor = "code"  # Editor.
explorer = "nautilus"  # File manager.
terminal = "kitty"  # Terminal.
quickapps = "kitty"  # Quick apps.
color_scheme = "prefer-dark"  # Color scheme.
gtk_theme = "adw-gtk3"  # GTK theme.